// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szklylvmdekzvfmnumuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6a2x5bHZtZGVrenZmbW51bXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjk3NzEsImV4cCI6MjA2NzcwNTc3MX0.2HUuMThcHV1Q58CxZJPdRw3GgNGNaS5jj4i9Nf_0fWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});